name:                afp-project
version:             0.1.0.0
github:              "PhiliPdB/afp-project"
license:             BSD3
author:              "Philip de Bruin, Jakub Młynek, Daniel van Vliet"
maintainer:          "p.debruin@students.uu.nl"
copyright:           "2021 Philip de Bruin, Jakub Młynek, Daniel van Vliet"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PhiliPdB/afp-project#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- hourglass

ghc-options:
- -Wall

library:
  source-dirs: src
  other-modules:
  - Data.TimeHelper
  dependencies:
  - vector

executables:
  afp-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - afp-project

tests:
  afp-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - afp-project
    - tasty >= 1.2.3
    - tasty-quickcheck >= 0.10.1.2
